// Make → Model → Variants for vehicles sold in India

export type MakesData = Record<string, Record<string, string[]>>;

export const CAR_MAKES_DATA: MakesData = {
  "Maruti Suzuki": {
    "Alto K10":      ["STD", "LXI", "VXI", "VXI+"],
    "Swift":         ["LXI", "VXI", "ZXI", "ZXI+", "VXI AMT", "ZXI AMT", "ZXI+ AMT"],
    "Baleno":        ["Sigma", "Delta", "Zeta", "Alpha", "Delta MT", "Zeta MT", "Alpha MT"],
    "Brezza":        ["LXI", "VXI", "ZXI", "ZXI+", "ZXI+ DT"],
    "Dzire":         ["LXI", "VXI", "ZXI", "ZXI+"],
    "WagonR":        ["LXI", "VXI", "VXI+", "ZXI", "ZXI+"],
    "Ertiga":        ["LXI", "VXI", "ZXI", "ZXI+"],
    "XL6":           ["Zeta", "Alpha", "Zeta+", "Alpha+"],
    "Fronx":         ["Sigma", "Delta", "Delta+", "Zeta", "Alpha"],
    "Grand Vitara":  ["Sigma", "Delta", "Zeta", "Alpha", "Alpha+"],
    "Invicto":       ["Zeta Plus", "Alpha Plus"],
    "Jimny":         ["Zeta", "Alpha"],
    "S-Presso":      ["STD", "LXI", "VXI", "VXI+"],
    "Celerio":       ["LXI", "VXI", "ZXI", "VXI CNG", "ZXI CNG"],
    "Ciaz":          ["Sigma", "Delta", "Zeta", "Alpha"],
  },
  "Hyundai": {
    "Grand i10 Nios": ["Era", "Magna", "Sportz", "Asta"],
    "i20":           ["Magna", "Sportz", "Asta", "Asta(O)", "N Line"],
    "Verna":         ["EX", "S", "S+", "SX", "SX(O)", "SX Turbo"],
    "Creta":         ["E", "EX", "S", "S(O)", "SX", "SX(O)", "SX Tech", "X Line"],
    "Venue":         ["E", "S", "S+", "SX", "SX+", "N Line"],
    "Alcazar":       ["Prestige", "Platinum", "Signature"],
    "Tucson":        ["Platinum", "Signature"],
    "Exter":         ["EX", "S", "SX", "SX(O)", "SX Tech", "SX(O) Connect"],
    "Aura":          ["E", "S", "SX", "SX+"],
    "Ioniq 5":       ["Standard Range", "Long Range"],
    "Ioniq 6":       ["Standard Range", "Long Range"],
    "Creta Electric":["E", "EX", "S", "SX", "SX Tech"],
  },
  "Tata": {
    "Punch":         ["Pure", "Adventure", "Accomplished", "Creative", "Accomplished A", "Creative A"],
    "Nexon":         ["Smart", "Smart+", "Pure", "Creative", "Fearless", "Fearless+"],
    "Nexon EV":      ["Medium Range", "Long Range", "Creative", "Fearless", "Fearless+"],
    "Tiago":         ["XE", "XT", "XZ", "XZ+", "NRG"],
    "Tiago EV":      ["XT", "XZ", "XZ+", "XZ+ Tech LUX"],
    "Tigor":         ["XE", "XT", "XZ", "XZ+"],
    "Altroz":        ["XE", "XM", "XT", "XZ", "XZ+", "XZ+ S"],
    "Harrier":       ["Smart", "Smart+", "Pure", "Adventure", "Fearless", "Fearless+"],
    "Safari":        ["Smart", "Smart+", "Pure", "Adventure", "Fearless", "Fearless+"],
    "Curvv":         ["Creative+", "Accomplished+", "Fearless+", "Fearless+S"],
    "Curvv EV":      ["Creative+", "Accomplished+", "Fearless+", "Fearless+S"],
  },
  "Mahindra": {
    "Thar":          ["LX 4-Str Hard Top", "LX 4-Str Soft Top", "LX 2-Str Hard Top"],
    "Thar Roxx":     ["MX1", "MX3", "MX5", "AX5 L", "AX7 L"],
    "Scorpio-N":     ["Z2", "Z4", "Z6", "Z6 L", "Z8", "Z8 L"],
    "Scorpio Classic":["S", "S3+", "S5", "S7", "S9", "S11"],
    "XUV700":        ["MX5", "AX3", "AX5", "AX5 L", "AX7", "AX7 L"],
    "XUV300":        ["W4", "W6", "W8", "W8(O)"],
    "XUV400":        ["EC Pro", "EL Pro"],
    "Bolero":        ["B4", "B6", "B8", "B9"],
    "BE 6e":         ["Pack One", "Pack Two", "Pack Three"],
    "XEV 9e":        ["Pack One", "Pack Two", "Pack Three"],
  },
  "Kia": {
    "Sonet":         ["HTE", "HTK", "HTK+", "HTX", "HTX+", "GTX+", "X-Line"],
    "Seltos":        ["HTE", "HTK", "HTK+", "HTX", "HTX+", "GTX+", "X-Line"],
    "Carens":        ["Premium", "Prestige", "Prestige+", "Luxury", "Luxury+"],
    "EV6":           ["Standard Range", "Long Range"],
    "EV9":           ["GT-Line"],
    "Syros":         ["HTE", "HTK", "HTK+", "HTX", "HTX+", "GTX"],
  },
  "Honda": {
    "Amaze":         ["S", "V", "VX", "ZX"],
    "City":          ["V", "VX", "ZX", "e:HEV V", "e:HEV ZX"],
    "Elevate":       ["V", "VX", "ZX"],
    "WR-V":          ["S", "V", "VX"],
    "Jazz":          ["S", "V", "VX"],
  },
  "Toyota": {
    "Innova Crysta":  ["G", "GX", "VX", "ZX"],
    "Innova Hycross": ["G", "VX", "ZX", "GX HEV", "VX HEV", "ZX HEV"],
    "Fortuner":       ["4x2 AT", "4x2 MT", "4x4 MT", "Legender 4x4 AT", "GR Sport"],
    "Glanza":         ["S", "G", "V"],
    "Urban Cruiser Hyryder": ["S", "G", "V", "E-Four"],
    "Camry":          ["Hybrid"],
    "Hilux":          ["Standard", "High"],
    "Land Cruiser":   ["LC 300", "Prado"],
  },
  "Renault": {
    "Kwid":          ["RXE", "RXL", "RXT", "RXT(O)", "Climber"],
    "Triber":        ["RXE", "RXL", "RXT", "RXZ"],
    "Kiger":         ["RXE", "RXL", "RXT", "RXZ", "RXZ Turbo CVT"],
  },
  "Nissan": {
    "Magnite":       ["XE", "XL", "XV", "XV Premium", "XV Premium Turbo CVT"],
  },
  "Volkswagen": {
    "Taigun":        ["Comfortline", "Highline", "Topline", "GT Plus Sport"],
    "Virtus":        ["Comfortline", "Highline", "Topline", "GT Plus Sport"],
    "Tiguan":        ["Elegance", "R-Line"],
    "Polo":          ["Trendline", "Comfortline", "Highline", "GT TSI"],
  },
  "Skoda": {
    "Slavia":        ["Active", "Ambition", "Style"],
    "Kushaq":        ["Active", "Ambition", "Style", "Monte Carlo"],
    "Octavia":       ["Style", "Style Plus"],
    "Superb":        ["L&K"],
    "Kodiaq":        ["Sportline", "L&K"],
  },
  "MG Motor": {
    "Hector":        ["Style", "Super", "Smart", "Sharp", "Savvy", "Blackstorm"],
    "Astor":         ["Style", "Super", "Sharp", "Pro", "Ultra"],
    "ZS EV":         ["Excite Pro", "Exclusive Pro"],
    "Comet EV":      ["N1", "N2", "N3", "N4"],
    "Gloster":       ["Super", "Sharp", "Savvy"],
    "Windsor EV":    ["Excite", "Excite Pro", "Essence"],
  },
  "Jeep": {
    "Compass":       ["Sport", "Longitude", "Limited", "Model S", "Night Eagle", "Trailhawk"],
    "Meridian":      ["Longitude", "Limited", "Overland"],
    "Wrangler":      ["Unlimited Sport", "Unlimited Rubicon"],
  },
  "Citroen": {
    "C3":            ["Live", "Feel", "Shine"],
    "C3 Aircross":   ["Feel", "Shine+", "Max"],
    "C5 Aircross":   ["Feel", "Shine"],
  },
  "BYD": {
    "Atto 3":        ["Standard", "Extended"],
    "Seal":          ["Dynamic", "Excellence"],
    "eMAX 7":        ["Standard", "Extended"],
  },
  "Audi": {
    "A4":            ["35 TFSI Premium", "35 TFSI Premium Plus", "40 TFSI Technology"],
    "A6":            ["45 TFSI Technology", "55 TFSI Technology"],
    "Q3":            ["35 TFSI Premium Plus", "40 TFSI Technology"],
    "Q5":            ["45 TFSI Technology", "45 TFSI Technology S"],
    "Q7":            ["45 TFSI Technology"],
    "Q8":            ["55 TFSI Technology", "SQ8"],
    "e-tron":        ["55 quattro", "S Performance"],
    "RS Q8":         ["RS Q8"],
  },
  "BMW": {
    "3 Series":      ["320d Luxury", "330i Sport", "M340i xDrive", "M3 Competition"],
    "5 Series":      ["520d Luxury", "530i Sport", "M5"],
    "7 Series":      ["740Li DPE", "740Li M Sport", "760Li M Sport"],
    "X1":            ["sDrive20i xLine", "sDrive18d xLine"],
    "X3":            ["xDrive20d xLine", "xDrive30i M Sport", "M40i"],
    "X5":            ["xDrive40i M Sport", "xDrive30d M Sport", "M50i"],
    "X7":            ["xDrive40i DPE", "xDrive40i M Sport"],
    "iX":            ["iX xDrive40 Sport"],
    "2 Series":      ["220i Gran Coupe Sport"],
  },
  "Mercedes-Benz": {
    "C-Class":       ["C 200 Progressive", "C 300 AMG Line", "AMG C 43 4MATIC"],
    "E-Class":       ["E 200 Progressive", "E 220d Progressive", "AMG E 53 4MATIC+"],
    "S-Class":       ["S 450 4MATIC", "S 500 4MATIC", "AMG S 63 E Performance"],
    "GLC":           ["GLC 200 Progressive", "GLC 300 4MATIC AMG Line", "AMG GLC 43"],
    "GLE":           ["GLE 300d 4MATIC", "GLE 450 4MATIC AMG Line", "AMG GLE 53"],
    "GLS":           ["GLS 450 4MATIC"],
    "EQS":           ["EQS 580 4MATIC"],
    "EQB":           ["EQB 300 4MATIC"],
    "A-Class":       ["A 200 Progressive", "A 200 AMG Line"],
  },
  "Volvo": {
    "XC40":          ["B3 Essential", "B4 Ultimate", "Recharge Ultimate"],
    "XC60":          ["B5 Essential", "B6 Ultimate", "Recharge Ultimate"],
    "XC90":          ["B5 Essential", "B6 Ultimate", "Recharge Ultimate"],
    "S60":           ["B4 R-Design"],
    "S90":           ["B6 Ultimate"],
  },
  "Force Motors": {
    "Gurkha":        ["3-Door Petrol", "3-Door Diesel", "5-Door Petrol", "5-Door Diesel"],
  },
};

export const BIKE_MAKES_DATA: MakesData = {
  "Hero MotoCorp": {
    "Splendor Plus":  ["Drum", "Self Drum", "Self Disc", "XTEC", "IBS"],
    "HF Deluxe":      ["Kick", "Self", "Self IBS"],
    "Passion Pro":    ["Drum", "Disc", "XTEC"],
    "Glamour":        ["Drum", "Disc", "XTEC"],
    "Xtreme 160R":    ["Standard", "Stealth 2.0", "Double Disc"],
    "Destini 125":    ["VX", "ZX", "Platinum"],
    "Maestro Edge 125":["Drum", "Disc", "Connect"],
    "Xoom 110":       ["Base", "VX"],
    "Karizma XMR":    ["Standard"],
    "Mavrick 440":    ["Standard"],
  },
  "Honda": {
    "Activa 6G":      ["STD", "DLX"],
    "Shine":          ["Drum", "Disc", "SP Disc"],
    "CB Hornet 2.0":  ["Standard", "CBS"],
    "SP 125":         ["Drum", "Disc", "Smart Disc"],
    "Dio":            ["STD", "DLX", "Sports"],
    "CB350 H'ness":   ["DLX", "DLX Pro"],
    "CB350 RS":       ["Standard"],
    "CB500F":         ["Standard", "ABS"],
    "CBR650R":        ["Standard"],
    "CB300R":         ["Standard"],
    "CB200X":         ["Standard"],
  },
  "Bajaj": {
    "Pulsar 150":     ["Std", "Twin Disc", "Neon"],
    "Pulsar N160":    ["Std", "DT"],
    "Pulsar N250":    ["Standard"],
    "Pulsar NS200":   ["Standard", "ABS"],
    "Pulsar RS200":   ["Standard", "ABS"],
    "Pulsar F250":    ["Standard"],
    "Platina 100":    ["Std", "Comfortec"],
    "CT110X":         ["Standard"],
    "Avenger Street 160": ["Standard"],
    "Avenger Cruise 220": ["Standard"],
    "Dominar 400":    ["Standard", "ABS"],
    "Chetak EV":      ["Urbane", "Premium", "Iconic"],
  },
  "TVS": {
    "Jupiter":        ["Std", "Classic", "Grande", "ZX", "Classic ET Fi"],
    "Apache RTR 160": ["4V Drum", "4V Disc", "4V Race Edition"],
    "Apache RTR 200 4V": ["Standard", "Race Edition"],
    "Apache RR 310":  ["Standard", "BTO"],
    "Ntorq 125":      ["Race Edition", "Race XP", "XT", "Super Squad"],
    "Raider 125":     ["Drum", "Disc", "Smart Connect"],
    "iQube":          ["S", "ST", "ST X"],
    "XL100":          ["Comfort", "HD"],
    "Sport":          ["Standard"],
  },
  "Royal Enfield": {
    "Classic 350":    ["Redditch", "Signals", "Dark", "Chrome", "Halcyon"],
    "Meteor 350":     ["Fireball", "Stellar", "Supernova"],
    "Bullet 350":     ["Standard", "ES"],
    "Hunter 350":     ["Dapper", "Rebel", "Metro", "Factory Custom"],
    "Himalayan":      ["Standard"],
    "Himalayan 450":  ["Standard", "Slide"],
    "Scram 411":      ["Standard"],
    "Guerrilla 450":  ["Standard", "Flash"],
    "Super Meteor 650":["Astral", "Celestial", "Interstellar"],
    "Interceptor 650":["Standard", "Mark 2"],
    "Continental GT 650": ["Standard", "Mark 2"],
    "Bear 650":       ["Standard"],
  },
  "Suzuki": {
    "Access 125":     ["Drum", "Disc", "Special Edition"],
    "Burgman Street 125": ["Std", "EX"],
    "Avenis 125":     ["Standard"],
    "Gixxer 150":     ["Standard", "SF", "SF MotoGP"],
    "Gixxer 250":     ["SF", "SF MotoGP"],
    "V-Strom 250 SX": ["Standard"],
    "Hayabusa":       ["Standard"],
    "GSX-S1000":      ["Standard", "GT"],
  },
  "Yamaha": {
    "FZ-S V4":        ["Standard", "DLX"],
    "FZ-X":           ["Standard"],
    "MT-15 V2":       ["Standard"],
    "R15 V4":         ["Standard", "M", "World GP 60th Anniversary"],
    "R15S":           ["Standard"],
    "Aerox 155":      ["Standard", "DLX", "S"],
    "Fascino 125":    ["Drum", "Disc", "Hybrid"],
    "Ray-ZR 125":     ["Drum", "Disc", "Hybrid"],
    "R7":             ["Standard"],
    "MT-07":          ["Standard"],
    "XSR155":         ["Standard"],
    "Tenere 700":     ["Standard"],
  },
  "KTM": {
    "Duke 125":       ["Standard"],
    "Duke 200":       ["Standard"],
    "Duke 250":       ["Standard"],
    "Duke 390":       ["Standard"],
    "RC 125":         ["Standard"],
    "RC 200":         ["Standard"],
    "RC 390":         ["Standard"],
    "Adventure 250":  ["Standard"],
    "Adventure 390":  ["Standard", "Rally"],
    "Adventure 790":  ["Standard"],
  },
  "Jawa": {
    "Classic 350":    ["Chrome", "Dual Channel ABS"],
    "42 FJ":          ["Standard"],
    "Perak":          ["Standard"],
    "42 Bobber":      ["Standard"],
  },
  "Triumph": {
    "Speed 400":      ["Standard"],
    "Scrambler 400X": ["Standard"],
    "Street Triple":  ["R", "RS"],
    "Tiger 900":      ["GT", "GT Pro", "Rally", "Rally Pro"],
    "Bonneville T100":["Standard"],
    "Bonneville T120":["Standard", "Black"],
    "Speed Triple 1200":["RS"],
    "Trident 660":    ["Standard"],
  },
  "Harley-Davidson": {
    "X440":           ["S", "V", "S Vivid", "V Vivid"],
    "Iron 883":       ["Standard"],
    "Sportster S":    ["Standard"],
    "Fat Bob":        ["114", "114 FXFBS"],
    "Street Glide":   ["Standard"],
    "Road Glide":     ["Standard"],
    "Fat Boy":        ["114"],
    "Pan America":    ["1250 Special"],
  },
  "BMW Motorrad": {
    "G 310 R":        ["Standard"],
    "G 310 GS":       ["Standard"],
    "F 850 GS":       ["Standard", "Adventure"],
    "S 1000 RR":      ["Standard", "M"],
    "S 1000 R":       ["Standard"],
    "R 1250 GS":      ["Standard", "Adventure"],
    "M 1000 RR":      ["Standard", "M"],
  },
  "Ola Electric": {
    "S1 Air":         ["Standard"],
    "S1 X":           ["2 kWh", "3 kWh", "4 kWh"],
    "S1 X+":          ["Standard"],
    "S1 Pro":         ["Gen 1", "Gen 2"],
    "S1 Pro+":        ["Standard"],
    "Roadster":       ["Standard", "X", "Pro"],
  },
  "Ather": {
    "450S":           ["Standard"],
    "450X":           ["Standard", "Pro"],
    "Rizta":          ["S", "Z"],
  },
  "Revolt": {
    "RV400":          ["Standard", "BRZ"],
    "RV1":            ["Standard"],
  },
};
